# Generated by Django 3.2.8 on 2021-11-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='writer',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
