# Generated by Django 3.2.8 on 2021-11-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='pic',
            field=models.ImageField(upload_to='vote/%y'),
        ),
    ]
