# Generated by Django 3.2.8 on 2021-11-03 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_choice_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='voter',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
