# Generated by Django 3.2.8 on 2021-11-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
